name: Deploy to Raspberry Pi
on: 
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy nathanrichard.dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install & Build App
        run: |
          npm install --legacy-peer-deps --force
          npm run build
      - name: deploy on raspberry pi
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "dist/"
          strip_components: 1
          target: "/var/www/test2"
